#ifndef __SubGUIClass__
#define __SubGUIClass__

/**
@file
Subclass of GUIClass, which is generated by wxFormBuilder.
*/

#include "GUIClass.h"
#include "Circuit.h"

//// end generated include

/** Implementing GUIClass */
class SubGUIClass : public GUIClass
{
protected:
	// Handlers for GUIClass events.
	void ExitClick(wxCommandEvent& event);
	void ShowAboutScreen(wxCommandEvent& event);
	void StartClick(wxCommandEvent& event);
	void NextStepClick(wxCommandEvent& event);
	void PauseClick(wxCommandEvent& event);
	void SearchForVector(wxFileDirPickerEvent& event);
public:
	/** Constructor */
	SubGUIClass(wxWindow* parent);
	//// end generated class members

private:
	Circuit* mainCircuit;

};

#endif // __SubGUIClass__
