#ifndef __TTTMainWindow__
#define __TTTMainWindow__

/**
@file
Subclass of MainWindow, which is generated by wxFormBuilder.
*/

#include "GUIClass.h"

//// end generated include

#include <string>

enum State { Blank, X, O, Draw };

/** Implementing MainWindow */
class SubGUIClass : public GUIClass
{
	protected:
		// Handlers for MainWindow events.
		void OnMainWindowClose( wxCloseEvent& event );
		void OnResetClick( wxCommandEvent& event );
		void OnExit( wxCommandEvent& event );
		void OnPlayerClick( wxCommandEvent& event );
	public:
		/** Constructor */
		SubGUIClass( wxWindow* parent );
	//// end generated class members
private:
	bool isOTurn = true;
	int moveCount = 0;
	State board[3][3] = { {Blank, Blank, Blank}, {Blank ,Blank, Blank}, {Blank, Blank, Blank} };
	State checkWinner(int x, int y, State s);
	void resetBoard();
};

#endif // __TTTMainWindow__
